name: whatsapp_clone
version: 1.0.0+1
publish_to: none
description: A Chat app that provides all kind of functionality a messaging app would provide
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.5

  #basic packages
  get: ^4.6.5                         #My state management 
  google_fonts: ^3.0.1                #fonts
  font_awesome_flutter: ^10.3.0       #icons
  flutter_screenutil: ^5.5.4          #used for responsive design
  dio: ^4.0.6                         #http client

  #Firebase packages
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8
  firebase_messaging: ^14.2.1

  #Notification
  # awesome_notifications_fcm: ^0.7.4+1
  # awesome_notifications: ^0.7.4+1

  #Storage packages
  get_storage: ^2.0.3           # key-value pair storage
  isar: ^3.0.5                  # No-SQL database
  isar_flutter_libs: ^3.0.5     # No-SQL database
  
  #image related packages
  extended_image: ^6.2.1        #used in image preview screen (to interact with the image)
  image_picker: ^0.8.6          #used to pick images (.....)          


  #video related packages
  chewie: ^1.4.0
  flutter_video_info:           # used to get video info (width,height)
  # video_viewer: ^1.2.7  

  #audio related packages
  voice_message_package: ^0.0.74
  flutter_sound: ^9.2.13
  
  #files related packages
  file_picker: ^5.2.4             # used to pick files

  #Random packages
  underline_indicator: ^0.0.4     # used in the home screen tabbar
  permission_handler: ^10.2.0     
  flutter_contacts: ^1.1.5+1      # Api to your phone contacts
  pinput: ^2.2.16                 # OTP field UI 
  url_launcher: ^6.1.7            # lanches links/opens files
  flutter_link_previewer: ^3.2.0  # used in text message bubble (to show preview for links)
  flutter_linkify: ^5.0.2         # used to highlight a url in a text
  uuid: ^3.0.7                    # Random Id generator
  pretty_qr_code: ^2.0.3          # generates a QR code       
  mobile_scanner: ^2.1.0          # reads Qr code
  intl: ^0.17.0
  sliver_header_delegate: ^0.0.5
  flutter_staggered_grid_view: ^0.6.2

  
  #Development packages
  logger: ^1.1.0
  exif: ^3.1.2
  image_size_getter: ^2.1.2
  video_player: ^2.5.1
  lottie: ^2.2.0
  
    
  #infinite_scroll_pagination: ^3.2.0  # used EVERY WHERE
  #flutter_chat_ui: ^1.6.6




dev_dependencies: 
  flutter_test: 
    sdk: flutter

  flutter_lints: ^2.0.1     # default package (comes with the project)
  build_runner: ^2.3.3      # code generator
  isar_generator: ^3.0.5    # code generator
  
  # it shows a photo of (your design) under the actual screen
  # (helps in programming the UI)
  pixel_perfect: ^1.1.1
    

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/lottie/
    


